### ISSUE TITLE
Why the feature outputs of BCNN is the outer product of the (only) one CNN and itself?

### ISSUE THREAD

**Issue by ideaRunner** [chencodeX/Bilinear_CNN_dog_classifi#11]
Hi, chencodeX

I think that the core codes of BCNN is the following codes from `bcnn_finetuning.py` in the end of class `vgg16`

``` python
        ''' Reshape conv5_3 from [batch_size, height, width, number_of_filters]
           to [batch_size, number_of_filters, height, width]'''
        self.conv5_3 = tf.transpose(self.conv5_3, perm=[0,3,1,2])


        ''' Reshape conv5_3 from [batch_size, number_of_filters, height*width] '''
        self.conv5_3 = tf.reshape(self.conv5_3,[-1,512,784])

        ''' A temporary variable which holds the transpose of conv5_3 '''
        conv5_3_T = tf.transpose(self.conv5_3, perm=[0,2,1])

        '''Matrix multiplication [batch_size,512,784] x [batch_size,784,512] '''
        self.phi_I = tf.matmul(self.conv5_3, conv5_3_T)
```
But I get confused when I try to understand it.

When I read the paper and other docs, I think that there must have **2 CNNs** and they get the outer product when combine the outputs of them, then we can connect it to FC layers or others.

But in the BCNN codes, when they build models, it seems like there is only **1 CNN** and it get outer product of it self.  

 I think 2 CNNs can extract different image features, but I don't understand the code of BCNN. 

Anything wrong of my understanding? Could you give me some suggestions? 

Thank you!

**Comment by chencodeX** [comment]
see issues#1

**Comment by ideaRunner** [comment]
Hi，

Thank you for your reply.

I will try to build asymmetry BCNN network.
