### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by konioyxgq** [chencodeX/Bilinear_CNN_dog_classifi#13]
在网络模型中，在BCNN的步骤中，做了如下的一个步骤：
 self.phi_I = tf.divide(self.phi_I,784.0)
这里为什么要除784啊？

**Comment by konioyxgq** [comment]
@chencodeX

**Comment by chencodeX** [comment]
这一步主要是用来做规范化。
往上看两行代码，self.phi_I = tf.einsum('ijkm,ijkn->imn',self.conv5_3,self.conv5_3)
我们对卷积提取出来的特征图谱，这两个矩阵计算了外积。外积这一步对所有的轴（784）进行了求和，所以我们可以对它进行一次标准化，以防止权重太大。
bcnn的paper  [BCNN](http://vis-www.cs.umass.edu/bcnn/docs/bcnn_iccv15.pdf)
