### ISSUE TITLE
image data

### ISSUE THREAD

**Issue by qiongxiao** [chencodeX/Bilinear_CNN_dog_classifi#4]
您好，这个源码的train_test文件夹里只有.txt文件，请问对应的图像数据在哪里？求这些数据集，可以付费，电子邮箱：xqlily@163.com

**Comment by chencodeX** [comment]
你需要这些狗的图像数据？

**Comment by qiongxiao** [comment]
是的，想要这个数据集,但是网上没找到下载地址，可以付费，电子邮箱：xqlily@163.com

**Comment by chencodeX** [comment]
我给你发邮件了
