### ISSUE TITLE
我想用这个来训练车的数据 可以吗

### ISSUE THREAD

**Issue by huatangzhi** [chencodeX/Bilinear_CNN_dog_classifi#5]

**Comment by chencodeX** [comment]
你可以利用项目中的模型来尝试进行车辆的细粒度分类，如果有什么问题，欢迎随时沟通。

**Comment by huatangzhi** [comment]
能看一下你的数据格式吗

**Comment by chencodeX** [comment]
都是普通的三通道彩色图像，不知道你需要了解哪些方面

**Comment by chencodeX** [comment]
本文采用的是one-hot编码，你只用注意修改模型的分类类别即可，pytorch的模型很灵活，你可以自由的选择数据的投喂方式。无论是使用官方的DataLoader，还是自己构建的数据装载器，都可以。本项目为了方便灵活的组织数据，所以采用的是自己设计数据装载程序。

**Comment by huatangzhi** [comment]
你那边测试那个效果会好一点？使用VGG还是其他

**Comment by chencodeX** [comment]
单纯的从准确率方面来说，对多个优化模型进行特征融合的效果是最好的。

**Comment by huatangzhi** [comment]
不用pytorch版本的话，只用到外面这几个文件吗
？

**Comment by huatangzhi** [comment]
all_pic_infsl 是怎么生成的

**Comment by chencodeX** [comment]
也可以的

**Comment by huatangzhi** [comment]
/home/meteo/zihao.chen/filter_ext/img_data/67/110.jpg 0  我的数据格式和你的这个结构一样，怎样能最快的完成代码修改，比如在哪个dataloader上修改。（时间比较紧，麻烦你了）

**Comment by chencodeX** [comment]
嗯，，还是不建议直接修改
