### ISSUE TITLE
请问这个均值是什么均值，怎么计算的

### ISSUE THREAD

**Issue by yxxhbgd** [chencodeX/Bilinear_CNN_dog_classifi#6]
with tf.name_scope('preprocess') as scope:
            mean = tf.constant([110.61220668946963, 127.15494646868024, 135.13440353131017]

这是整个数据集图片的均值吗

**Comment by chencodeX** [comment]
rgb三个通道的均值，计算就是直接求和平均

在 2018年4月19日 下午3:15，yxxhbgd <notifications@github.com>写道：

with tf.name_scope('preprocess') as scope:
mean = tf.constant([110.61220668946963, 127.15494646868024, 135.13440353131017]

这是整个数据集图片的均值吗

―

**Comment by yxxhbgd** [comment]
好的，谢谢您
