### ISSUE TITLE
生成hdf5数据时错误

### ISSUE THREAD

**Issue by yxxhbgd** [chencodeX/Bilinear_CNN_dog_classifi#7]
我用的时stanford dogs数据集，当对测试集数据生成hdf5格式时成功，但是对训练集数据生成hdf5格式时报错：
![dzkl 6y z_n giz z_ lp](https://user-images.githubusercontent.com/30422248/38988753-f92a3db0-4406-11e8-9bbc-3002a6eafbbe.png)
请问是什么原因

**Comment by chencodeX** [comment]
数据格式对不上，建议你检查一下数据集。



发自我的小米手机
在 yxxhbgd <notifications@github.com>，2018年4月19日 下午7:22写道：

我用的时stanford dogs数据集，当对测试集数据生成hdf5格式时成功，但是对训练集数据生成hdf5格式时报错：
[dzkl 6y z_n giz z_ lp]<https://user-images.githubusercontent.com/30422248/38988753-f92a3db0-4406-11e8-9bbc-3002a6eafbbe.png>
请问是什么原因
