### ISSUE TITLE
bcnn_DD_woft.py和bcnn_finetuning.py

### ISSUE THREAD

**Issue by yxxhbgd** [chencodeX/Bilinear_CNN_dog_classifi#8]
您好，请问bcnn_DD_woft.py和bcnn_finetuning.py这两个文件，前者只训练最后全连接层，后者finetune整个网络，请问这两个训练过程有什么关系吗，因为我看到后者的网络还是使用的最初始的vgg16_weights.npz

**Comment by chencodeX** [comment]
有联系，bcnn_DD_woft.py只训练全连接层，并将参数保留下来，bcnn_finetuning.py使用训练好的全连接层参数微调整个BCNN网络

**Comment by yxxhbgd** [comment]
请问参数保留在哪里了，在bcnn_finetuning.py文件里面体现出来了吗，还是参数直接保留在vgg16_weights.npz里面了？

**Comment by chencodeX** [comment]
bcnn_DD_woft.py 的349行

**Comment by yxxhbgd** [comment]
非常感谢

**Comment by longintlong** [comment]
我想问一下349行为什么保存的文件名是last_layers_epoch_15.npz，但是在finetuning文件中读取的是
last_layers_epoch_15_448.npz

**Comment by chencodeX** [comment]
这不重要，我中间调试了几次不同的图像比例尝试效果，但是没有明显提升


________________________________
发件人: longintlong <notifications@github.com>
发送时间: Sunday, October 28, 2018 2:41:41 PM
收件人: chencodeX/Bilinear_CNN_dog_classifi
抄送: 陈子豪; State change
主题: Re: [chencodeX/Bilinear_CNN_dog_classifi] bcnn_DD_woft.py和bcnn_finetuning.py (#8)


我想问一下349行为什么保存的文件名是last_layers_epoch_15.npz，但是在finetuning文件中读取的是
last_layers_epoch_15_448.npz

―

**Comment by longintlong** [comment]
ok，非常感谢~




------------------ 原始邮件 ------------------
发件人: "陈子豪"<notifications@github.com>;
发送时间: 2018年10月28日(星期天) 晚上6:08
收件人: "chencodeX/Bilinear_CNN_dog_classifi"<Bilinear_CNN_dog_classifi@noreply.github.com>;
抄送: "易透达春绿"<747099367@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [chencodeX/Bilinear_CNN_dog_classifi] bcnn_DD_woft.py和bcnn_finetuning.py (#8)



这不重要，我中间调试了几次不同的图像比例尝试效果，但是没有明显提升
 
 
 ________________________________
 发件人: longintlong <notifications@github.com>
 发送时间: Sunday, October 28, 2018 2:41:41 PM
 收件人: chencodeX/Bilinear_CNN_dog_classifi
 抄送: 陈子豪; State change
 主题: Re: [chencodeX/Bilinear_CNN_dog_classifi] bcnn_DD_woft.py和bcnn_finetuning.py (#8)
 
 
 我想问一下349行为什么保存的文件名是last_layers_epoch_15.npz，但是在finetuning文件中读取的是
 last_layers_epoch_15_448.npz
 
 ―
